all:stra lcs tro floyd

stra:magar_pa2_stra.c
	gcc -g magar_pa2_stra.c -o stra

lcs:magar_pa2_lcs.c
	gcc -g magar_pa2_lcs.c -o lcs

tro:magar_pa2_tro.c
	gcc -g magar_pa2_tro.c -o tro -lm

floyd:magar_pa2_floyd.c
	gcc -g magar_pa2_floyd.c -o floyd

clean:
	rm stra tro lcs floyd
